name: pdf2word
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip>=20.0
  - pip:
    - PyMuPDF>=1.19.0
    - python-docx>=0.8.10
    - fonttools>=4.24.0
    - numpy>=1.17.2
    - opencv-python-headless>=4.5
    - fire>=0.3.0 